//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using System.Xml.Serialization;

/* method-1 using xml serialization

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.dhcs.ca.gov/SDMCP2/EFTEnrollment")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.dhcs.ca.gov/SDMCP2/EFTEnrollment", IsNullable=false)]
public partial class EFTEnrollment {
    
    private int eftEnrollIDField;
    
    private string providerNameField;
    
    private string providerBusinessNameField;
    
    private string prvStreetAddressField;
    
    private string prvCityField;
    
    private string prvStateProvinceField;
    
    private string prvZipPostalCodeField;
    
    private decimal prvTINorEINField;
    
    private decimal prvNPIField;
    
    private string assigningAuthorityField;
    
    private string tradingPartnerIDField;
    
    private string prvContactNameField;
    
    private string prvContactTitleField;
    
    private decimal prvContactPhoneField;
    
    private System.Nullable<decimal> prvContactPhoneExtField;
    
    private bool prvContactPhoneExtFieldSpecified;
    
    private string prvContactEmailField;
    
    private System.Nullable<decimal> prvContactFaxField;
    
    private bool prvContactFaxFieldSpecified;
    
    private string prvAgentNameField;
    
    private string prvAgentStreetField;
    
    private string prvAgentCityField;
    
    private string prvAgentStateProvinceField;
    
    private string prvAgentZipCodeField;
    
    private string prvAContactNameField;
    
    private string prvAContactTitleField;
    
    private System.Nullable<decimal> prvAContactPhoneField;
    
    private bool prvAContactPhoneFieldSpecified;
    
    private System.Nullable<decimal> prvAContactPhoneExtField;
    
    private bool prvAContactPhoneExtFieldSpecified;
    
    private string prvAContactEmailField;
    
    private System.Nullable<decimal> prvAContactFaxField;
    
    private bool prvAContactFaxFieldSpecified;
    
    private string fINameField;
    
    private string fIStreetField;
    
    private string fICityField;
    
    private string fIStateProvinceField;
    
    private string fIZipCodeField;
    
    private decimal fIPhoneField;
    
    private System.Nullable<decimal> fIPhoneExtField;
    
    private bool fIPhoneExtFieldSpecified;
    
    private decimal fIRoutingNumberField;
    
    private string fIAccountTypeField;
    
    private string prvAccountNoField;
    
    private System.Nullable<decimal> prvIdentifierTINField;
    
    private bool prvIdentifierTINFieldSpecified;
    
    private System.Nullable<decimal> prvIdentifierNPIField;
    
    private bool prvIdentifierNPIFieldSpecified;
    
    private string reasonForSubmissionField;
    
    private string bankLetterNameField;
    
    private string printedNameOfPersonField;
    
    private string titleOfPersonField;
    
    private System.Nullable<System.DateTime> dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private System.Nullable<System.DateTime> eRAEffectiveDateField;
    
    private bool eRAEffectiveDateFieldSpecified;
    
    private int sysIDField;
    
    private string orgIDField;
    
    private string iTWSUSerID_SubmitterField;
    
    private string iTWSUserID_PInfoApproverField;
    
    private string iTWSUserID_FInfoApproverField;
    
    private string pInfoApproved_YNField;
    
    private string fInfoApproved_YNField;
    
    private System.Nullable<System.DateTime> pInfoDecissionDateField;
    
    private bool pInfoDecissionDateFieldSpecified;
    
    private System.Nullable<System.DateTime> fInfoDecissionDateField;
    
    private bool fInfoDecissionDateFieldSpecified;
    
    private string pInfoRejectionReasonField;
    
    private string fInfoRejectionReasonField;
    
    private string gUIDField;
    
    private string iTWSUserEmail_SubmitterField;
    
    private string bankLetterFormattedNameField;
    
    private string bankLetterField;
    
    /// <remarks/>
    public int EftEnrollID {
        get {
            return this.eftEnrollIDField;
        }
        set {
            this.eftEnrollIDField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderName {
        get {
            return this.providerNameField;
        }
        set {
            this.providerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ProviderBusinessName {
        get {
            return this.providerBusinessNameField;
        }
        set {
            this.providerBusinessNameField = value;
        }
    }
    
    /// <remarks/>
    public string PrvStreetAddress {
        get {
            return this.prvStreetAddressField;
        }
        set {
            this.prvStreetAddressField = value;
        }
    }
    
    /// <remarks/>
    public string PrvCity {
        get {
            return this.prvCityField;
        }
        set {
            this.prvCityField = value;
        }
    }
    
    /// <remarks/>
    public string PrvStateProvince {
        get {
            return this.prvStateProvinceField;
        }
        set {
            this.prvStateProvinceField = value;
        }
    }
    
    /// <remarks/>
    public string PrvZipPostalCode {
        get {
            return this.prvZipPostalCodeField;
        }
        set {
            this.prvZipPostalCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal PrvTINorEIN {
        get {
            return this.prvTINorEINField;
        }
        set {
            this.prvTINorEINField = value;
        }
    }
    
    /// <remarks/>
    public decimal PrvNPI {
        get {
            return this.prvNPIField;
        }
        set {
            this.prvNPIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AssigningAuthority {
        get {
            return this.assigningAuthorityField;
        }
        set {
            this.assigningAuthorityField = value;
        }
    }
    
    /// <remarks/>
    public string TradingPartnerID {
        get {
            return this.tradingPartnerIDField;
        }
        set {
            this.tradingPartnerIDField = value;
        }
    }
    
    /// <remarks/>
    public string PrvContactName {
        get {
            return this.prvContactNameField;
        }
        set {
            this.prvContactNameField = value;
        }
    }
    
    /// <remarks/>
    public string PrvContactTitle {
        get {
            return this.prvContactTitleField;
        }
        set {
            this.prvContactTitleField = value;
        }
    }
    
    /// <remarks/>
    public decimal PrvContactPhone {
        get {
            return this.prvContactPhoneField;
        }
        set {
            this.prvContactPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvContactPhoneExt {
        get {
            return this.prvContactPhoneExtField;
        }
        set {
            this.prvContactPhoneExtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvContactPhoneExtSpecified {
        get {
            return this.prvContactPhoneExtFieldSpecified;
        }
        set {
            this.prvContactPhoneExtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string PrvContactEmail {
        get {
            return this.prvContactEmailField;
        }
        set {
            this.prvContactEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvContactFax {
        get {
            return this.prvContactFaxField;
        }
        set {
            this.prvContactFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvContactFaxSpecified {
        get {
            return this.prvContactFaxFieldSpecified;
        }
        set {
            this.prvContactFaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAgentName {
        get {
            return this.prvAgentNameField;
        }
        set {
            this.prvAgentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAgentStreet {
        get {
            return this.prvAgentStreetField;
        }
        set {
            this.prvAgentStreetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAgentCity {
        get {
            return this.prvAgentCityField;
        }
        set {
            this.prvAgentCityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAgentStateProvince {
        get {
            return this.prvAgentStateProvinceField;
        }
        set {
            this.prvAgentStateProvinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAgentZipCode {
        get {
            return this.prvAgentZipCodeField;
        }
        set {
            this.prvAgentZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAContactName {
        get {
            return this.prvAContactNameField;
        }
        set {
            this.prvAContactNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAContactTitle {
        get {
            return this.prvAContactTitleField;
        }
        set {
            this.prvAContactTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvAContactPhone {
        get {
            return this.prvAContactPhoneField;
        }
        set {
            this.prvAContactPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvAContactPhoneSpecified {
        get {
            return this.prvAContactPhoneFieldSpecified;
        }
        set {
            this.prvAContactPhoneFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvAContactPhoneExt {
        get {
            return this.prvAContactPhoneExtField;
        }
        set {
            this.prvAContactPhoneExtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvAContactPhoneExtSpecified {
        get {
            return this.prvAContactPhoneExtFieldSpecified;
        }
        set {
            this.prvAContactPhoneExtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PrvAContactEmail {
        get {
            return this.prvAContactEmailField;
        }
        set {
            this.prvAContactEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvAContactFax {
        get {
            return this.prvAContactFaxField;
        }
        set {
            this.prvAContactFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvAContactFaxSpecified {
        get {
            return this.prvAContactFaxFieldSpecified;
        }
        set {
            this.prvAContactFaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string FIName {
        get {
            return this.fINameField;
        }
        set {
            this.fINameField = value;
        }
    }
    
    /// <remarks/>
    public string FIStreet {
        get {
            return this.fIStreetField;
        }
        set {
            this.fIStreetField = value;
        }
    }
    
    /// <remarks/>
    public string FICity {
        get {
            return this.fICityField;
        }
        set {
            this.fICityField = value;
        }
    }
    
    /// <remarks/>
    public string FIStateProvince {
        get {
            return this.fIStateProvinceField;
        }
        set {
            this.fIStateProvinceField = value;
        }
    }
    
    /// <remarks/>
    public string FIZipCode {
        get {
            return this.fIZipCodeField;
        }
        set {
            this.fIZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal FIPhone {
        get {
            return this.fIPhoneField;
        }
        set {
            this.fIPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> FIPhoneExt {
        get {
            return this.fIPhoneExtField;
        }
        set {
            this.fIPhoneExtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FIPhoneExtSpecified {
        get {
            return this.fIPhoneExtFieldSpecified;
        }
        set {
            this.fIPhoneExtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal FIRoutingNumber {
        get {
            return this.fIRoutingNumberField;
        }
        set {
            this.fIRoutingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string FIAccountType {
        get {
            return this.fIAccountTypeField;
        }
        set {
            this.fIAccountTypeField = value;
        }
    }
    
    /// <remarks/>
    public string PrvAccountNo {
        get {
            return this.prvAccountNoField;
        }
        set {
            this.prvAccountNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvIdentifierTIN {
        get {
            return this.prvIdentifierTINField;
        }
        set {
            this.prvIdentifierTINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvIdentifierTINSpecified {
        get {
            return this.prvIdentifierTINFieldSpecified;
        }
        set {
            this.prvIdentifierTINFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PrvIdentifierNPI {
        get {
            return this.prvIdentifierNPIField;
        }
        set {
            this.prvIdentifierNPIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrvIdentifierNPISpecified {
        get {
            return this.prvIdentifierNPIFieldSpecified;
        }
        set {
            this.prvIdentifierNPIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ReasonForSubmission {
        get {
            return this.reasonForSubmissionField;
        }
        set {
            this.reasonForSubmissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BankLetterName {
        get {
            return this.bankLetterNameField;
        }
        set {
            this.bankLetterNameField = value;
        }
    }
    
    /// <remarks/>
    public string PrintedNameOfPerson {
        get {
            return this.printedNameOfPersonField;
        }
        set {
            this.printedNameOfPersonField = value;
        }
    }
    
    /// <remarks/>
    public string TitleOfPerson {
        get {
            return this.titleOfPersonField;
        }
        set {
            this.titleOfPersonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> ERAEffectiveDate {
        get {
            return this.eRAEffectiveDateField;
        }
        set {
            this.eRAEffectiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ERAEffectiveDateSpecified {
        get {
            return this.eRAEffectiveDateFieldSpecified;
        }
        set {
            this.eRAEffectiveDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int SysID {
        get {
            return this.sysIDField;
        }
        set {
            this.sysIDField = value;
        }
    }
    
    /// <remarks/>
    public string OrgID {
        get {
            return this.orgIDField;
        }
        set {
            this.orgIDField = value;
        }
    }
    
    /// <remarks/>
    public string ITWSUSerID_Submitter {
        get {
            return this.iTWSUSerID_SubmitterField;
        }
        set {
            this.iTWSUSerID_SubmitterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ITWSUserID_PInfoApprover {
        get {
            return this.iTWSUserID_PInfoApproverField;
        }
        set {
            this.iTWSUserID_PInfoApproverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ITWSUserID_FInfoApprover {
        get {
            return this.iTWSUserID_FInfoApproverField;
        }
        set {
            this.iTWSUserID_FInfoApproverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PInfoApproved_YN {
        get {
            return this.pInfoApproved_YNField;
        }
        set {
            this.pInfoApproved_YNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FInfoApproved_YN {
        get {
            return this.fInfoApproved_YNField;
        }
        set {
            this.fInfoApproved_YNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> PInfoDecissionDate {
        get {
            return this.pInfoDecissionDateField;
        }
        set {
            this.pInfoDecissionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PInfoDecissionDateSpecified {
        get {
            return this.pInfoDecissionDateFieldSpecified;
        }
        set {
            this.pInfoDecissionDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> FInfoDecissionDate {
        get {
            return this.fInfoDecissionDateField;
        }
        set {
            this.fInfoDecissionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FInfoDecissionDateSpecified {
        get {
            return this.fInfoDecissionDateFieldSpecified;
        }
        set {
            this.fInfoDecissionDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PInfoRejectionReason {
        get {
            return this.pInfoRejectionReasonField;
        }
        set {
            this.pInfoRejectionReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FInfoRejectionReason {
        get {
            return this.fInfoRejectionReasonField;
        }
        set {
            this.fInfoRejectionReasonField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ITWSUserEmail_Submitter {
        get {
            return this.iTWSUserEmail_SubmitterField;
        }
        set {
            this.iTWSUserEmail_SubmitterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BankLetterFormattedName {
        get {
            return this.bankLetterFormattedNameField;
        }
        set {
            this.bankLetterFormattedNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BankLetter {
        get {
            return this.bankLetterField;
        }
        set {
            this.bankLetterField = value;
        }
    }


*/


#region old EFTEnrollment implementation class
namespace EAMITestClient
{

    public class EFTEnrollment
    {
        public EFTEnrollment(XDocument xdoc)
        {
            LoadPropertiesFromXml(xdoc);
        }




        public int EftEnrollID { get; set; }
        public string ProviderName { get; set; }
        public string ProviderBusinessName { get; set; }
        public string PrvStreetAddress { get; set; }
        public string PrvCity { get; set; }
        public string PrvStateProvince { get; set; }
        public string PrvZipPostalCode { get; set; }
        public string PrvTINorEIN { get; set; }
        public string PrvNPI { get; set; }


        public string AssigningAuthority { get; set; }
        public string TradingPartnerID { get; set; }


        public string PrvContactName { get; set; }
        public string PrvContactTitle { get; set; }
        public string PrvContactPhone { get; set; }
        public string PrvContactPhoneExt { get; set; }
        public string PrvContactEmail { get; set; }
        public string PrvContactFax { get; set; }


        public string PrvAgentName { get; set; }
        public string PrvAgentStreet { get; set; }
        public string PrvAgentCity { get; set; }
        public string PrvAgentStateProvince { get; set; }
        public string PrvAgentZipCode { get; set; }


        public string PrvAContactName { get; set; }
        public string PrvAContactTitle { get; set; }
        public string PrvAContactPhone { get; set; }
        public string PrvAContactPhoneExt { get; set; }
        public string PrvAContactEmail { get; set; }
        public string PrvAContactFax { get; set; }


        public string FIName { get; set; }
        public string FIStreet { get; set; }
        public string FICity { get; set; }
        public string FIStateProvince { get; set; }
        public string FIZipCode { get; set; }
        public string FIPhone { get; set; }
        public string FIPhoneExt { get; set; }
        public string FIRoutingNumber { get; set; }
        public string FIAccountType { get; set; }


        public string PrvAccountNo { get; set; }
        public string PrvIdentifierTIN { get; set; }
        public string PrvIdentifierNPI { get; set; }
        public string ReasonForSubmission { get; set; }
        public string BankLetterName { get; set; }
        public string PrintedNameOfPerson { get; set; }
        public string TitleOfPerson { get; set; }
        public string DateCreated { get; set; }
        public string ERAEffectiveDate { get; set; }


        public string SysID { get; set; }
        public string OrgID { get; set; }
        public string ITWSUSerID_Submitter { get; set; }
        public string ITWSUserID_PInfoApprover { get; set; }
        public string ITWSUserID_FInfoApprover { get; set; }
        public string PInfoApproved_YN { get; set; }
        public string FInfoApproved_YN { get; set; }
        public string PInfoDecissionDate { get; set; }
        public string FInfoDecissionDate { get; set; }
        public string PInfoRejectionReason { get; set; }
        public string FInfoRejectionReason { get; set; }
        public string GUID { get; set; }
        public string ITWSUserEmail_Submitter { get; set; }
        public string BankLetterFormattedName { get; set; }




        private void LoadPropertiesFromXml(XDocument xdoc)
        {


            //foreach (XElement xe in xdoc.Root.Descendants("EFTEnrollment"))
            //{
            //    Console.WriteLine(xe.Name + "  " + xe.Value); 

            //}
            //return;

            //XNamespace ns = "http://www.dhcs.ca.gov/SDMCP2/EFTEnrollment";

            //var fields = xdoc.Descendants(ns + "EFTEnrollment").Where(x => (string)x.Attribute("name") == "ProviderName").FirstOrDefault();

            //foreach (XElement element in xdoc.Root
            //                    .Element(ns + "fields")
            //                    .Elements(ns + "field"))
            //{
            //    Console.WriteLine("Name: {0}; Value: {1}",
            //                      (string)element.Attribute("name"),
            //                      (string)element.Element(ns + "value"));
            //}



            XElement xeRoot = xdoc.Element("EFTEnrollment");
            XElement xeRoot2 = xdoc.Root;

            List<XElement> xeList = xdoc.Root.Elements().ToList();
            this.EftEnrollID = int.Parse(xeList.FirstOrDefault(x => x.Name.LocalName == "EftEnrollID").Value);



            string mmyValue = xeRoot2.Elements().Where(x => x.Name.LocalName == "EftEnrollID").FirstOrDefault().Value;

            //foreach(XElement xe in xeRoot2.Elements())
            //{
            //    switch(xe.Name.LocalName)
            //    {
            //        case "EftEnrollID":
            //            this.EftEnrollID = int.Parse(xe.Value));
            //            break;

            //    }
            //}

            this.EftEnrollID = int.Parse(xeRoot.Element("EftEnrollID").Value);
            this.ProviderName = xeRoot.Element("ProviderName").Value;
            this.ProviderBusinessName = xeRoot.Element("ProviderBusinessName").Value;
            this.PrvStreetAddress = xeRoot.Element("PrvStreetAddress").Value;
            this.PrvCity = xeRoot.Element("PrvCity").Value;
            this.PrvStateProvince = xeRoot.Element("PrvStateProvince").Value;
            this.PrvZipPostalCode = xeRoot.Element("PrvZipPostalCode").Value;
            this.PrvTINorEIN = xeRoot.Element("PrvTINorEIN").Value;
            this.PrvNPI = xeRoot.Element("PrvNPI").Value;

            this.AssigningAuthority = xeRoot.Element("AssigningAuthority").Value;
            this.TradingPartnerID = xeRoot.Element("TradingPartnerID").Value;

            this.PrvContactName = xeRoot.Element("PrvContactName").Value;
            this.PrvContactTitle = xeRoot.Element("PrvContactTitle").Value;
            this.PrvContactPhone = xeRoot.Element("PrvContactPhone").Value;
            this.PrvContactPhoneExt = xeRoot.Element("PrvContactPhoneExt").Value;
            this.PrvContactEmail = xeRoot.Element("PrvContactEmail").Value;
            this.PrvContactFax = xeRoot.Element("PrvContactFax").Value;


            this.PrvAgentName = xeRoot.Element("PrvAgentName").Value;
            this.PrvAgentStreet = xeRoot.Element("PrvAgentStreet").Value;
            this.PrvAgentCity = xeRoot.Element("PrvAgentCity").Value;
            this.PrvAgentStateProvince = xeRoot.Element("PrvAgentStateProvince").Value;
            this.PrvAgentZipCode = xeRoot.Element("PrvAgentZipCode").Value;


            this.PrvAContactName = xeRoot.Element("PrvAContactName").Value;
            this.PrvAContactTitle = xeRoot.Element("PrvAContactTitle").Value;
            this.PrvAContactPhone = xeRoot.Element("PrvAContactPhone").Value;
            this.PrvAContactPhoneExt = xeRoot.Element("PrvAContactPhoneExt").Value;
            this.PrvAContactEmail = xeRoot.Element("PrvAContactEmail").Value;
            this.PrvAContactFax = xeRoot.Element("PrvAContactFax").Value;


            this.FIName = xeRoot.Element("FIName").Value;
            this.FIStreet = xeRoot.Element("FIStreet").Value;
            this.FICity = xeRoot.Element("FICity").Value;
            this.FIStateProvince = xeRoot.Element("FIStateProvince").Value;
            this.FIZipCode = xeRoot.Element("FIZipCode").Value;
            this.FIPhone = xeRoot.Element("FIPhone").Value;
            this.FIPhoneExt = xeRoot.Element("FIPhoneExt").Value;
            this.FIRoutingNumber = xeRoot.Element("FIRoutingNumber").Value;
            this.FIAccountType = xeRoot.Element("FIAccountType").Value;


            this.PrvAccountNo = xeRoot.Element("PrvAccountNo").Value;
            this.PrvIdentifierTIN = xeRoot.Element("PrvIdentifierTIN").Value;
            this.PrvIdentifierNPI = xeRoot.Element("PrvIdentifierNPI").Value;
            this.ReasonForSubmission = xeRoot.Element("ReasonForSubmission").Value;
            this.BankLetterName = xeRoot.Element("BankLetterName").Value;
            this.PrintedNameOfPerson = xeRoot.Element("PrintedNameOfPerson").Value;
            this.TitleOfPerson = xeRoot.Element("TitleOfPerson").Value;
            this.DateCreated = xeRoot.Element("DateCreated").Value;
            this.ERAEffectiveDate = xeRoot.Element("ERAEffectiveDate").Value;


            this.SysID = xeRoot.Element("SysID").Value;
            this.OrgID = xeRoot.Element("OrgID").Value;
            this.ITWSUSerID_Submitter = xeRoot.Element("ITWSUSerID_Submitter").Value;
            this.ITWSUserID_PInfoApprover = xeRoot.Element("ITWSUserID_PInfoApprover").Value;
            this.ITWSUserID_FInfoApprover = xeRoot.Element("ITWSUserID_FInfoApprover").Value;
            this.PInfoApproved_YN = xeRoot.Element("PInfoApproved_YN").Value;
            this.FInfoApproved_YN = xeRoot.Element("FInfoApproved_YN").Value;
            this.PInfoDecissionDate = xeRoot.Element("PInfoDecissionDate").Value;
            this.FInfoDecissionDate = xeRoot.Element("FInfoDecissionDate").Value;
            this.PInfoRejectionReason = xeRoot.Element("PInfoRejectionReason").Value;
            this.FInfoRejectionReason = xeRoot.Element("FInfoRejectionReason").Value;
            this.GUID = xeRoot.Element("GUID").Value;
            this.ITWSUserEmail_Submitter = xeRoot.Element("ITWSUserEmail_Submitter").Value;
            this.BankLetterFormattedName = xeRoot.Element("BankLetterFormattedName").Value;
        }
    }
}
  

#endregion







