//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAMITestClient.EAMISvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EAMITransaction", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentStatusInquiryRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentStatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentSubmissionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentStatusInquiryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentSubmissionRequest))]
    public partial class EAMITransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenderIDField;
        
        private string ReceiverIDField;
        
        private string TransactionIDField;
        
        private EAMITestClient.EAMISvcRef.TransactionType TransactionTypeField;
        
        private string TransactionVersionField;
        
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDField, value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string ReceiverID {
            get {
                return this.ReceiverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDField, value) != true)) {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public EAMITestClient.EAMISvcRef.TransactionType TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TransactionVersion {
            get {
                return this.TransactionVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionVersionField, value) != true)) {
                    this.TransactionVersionField = value;
                    this.RaisePropertyChanged("TransactionVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatusInquiryRequest", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentStatusInquiryRequest : EAMITestClient.EAMISvcRef.EAMITransaction {
        
        private string PaymentRecordCountField;
        
        private System.Collections.Generic.List<EAMITestClient.EAMISvcRef.BaseRecord> PaymentRecordListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentRecordCount {
            get {
                return this.PaymentRecordCountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordCountField, value) != true)) {
                    this.PaymentRecordCountField = value;
                    this.RaisePropertyChanged("PaymentRecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<EAMITestClient.EAMISvcRef.BaseRecord> PaymentRecordList {
            get {
                return this.PaymentRecordListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordListField, value) != true)) {
                    this.PaymentRecordListField = value;
                    this.RaisePropertyChanged("PaymentRecordList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentSubmissionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentStatusInquiryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryResponse))]
    public partial class PaymentStatusResponse : EAMITestClient.EAMISvcRef.EAMITransaction {
        
        private string ResponseStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseStatusCode {
            get {
                return this.ResponseStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseStatusCodeField, value) != true)) {
                    this.ResponseStatusCodeField = value;
                    this.RaisePropertyChanged("ResponseStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentSubmissionResponse", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentSubmissionResponse : EAMITestClient.EAMISvcRef.PaymentStatusResponse {
        
        private System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecordStatus> PaymentRecordStatuListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecordStatus> PaymentRecordStatuList {
            get {
                return this.PaymentRecordStatuListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordStatuListField, value) != true)) {
                    this.PaymentRecordStatuListField = value;
                    this.RaisePropertyChanged("PaymentRecordStatuList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatusInquiryResponse", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentStatusInquiryResponse : EAMITestClient.EAMISvcRef.PaymentStatusResponse {
        
        private System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecordStatusPlus> PaymentRecordStatuListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecordStatusPlus> PaymentRecordStatuList {
            get {
                return this.PaymentRecordStatuListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordStatuListField, value) != true)) {
                    this.PaymentRecordStatuListField = value;
                    this.RaisePropertyChanged("PaymentRecordStatuList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RejectedPaymentInquiryResponse", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class RejectedPaymentInquiryResponse : EAMITestClient.EAMISvcRef.PaymentStatusResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecordStatus> PaymentRecordStatuListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecordStatus> PaymentRecordStatuList {
            get {
                return this.PaymentRecordStatuListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordStatuListField, value) != true)) {
                    this.PaymentRecordStatuListField = value;
                    this.RaisePropertyChanged("PaymentRecordStatuList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RejectedPaymentInquiryRequest", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class RejectedPaymentInquiryRequest : EAMITestClient.EAMISvcRef.EAMITransaction {
        
        private System.DateTime RejectedDateFromField;
        
        private System.DateTime RejectedDateToField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime RejectedDateFrom {
            get {
                return this.RejectedDateFromField;
            }
            set {
                if ((this.RejectedDateFromField.Equals(value) != true)) {
                    this.RejectedDateFromField = value;
                    this.RaisePropertyChanged("RejectedDateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime RejectedDateTo {
            get {
                return this.RejectedDateToField;
            }
            set {
                if ((this.RejectedDateToField.Equals(value) != true)) {
                    this.RejectedDateToField = value;
                    this.RaisePropertyChanged("RejectedDateTo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentSubmissionRequest", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentSubmissionRequest : EAMITestClient.EAMISvcRef.EAMITransaction {
        
        private string PaymentRecordCountField;
        
        private string PaymentRecordTotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EAMITestClient.EAMISvcRef.PaymentExchangeEntity PayerInfoField;
        
        private System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecord> PaymentRecordListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentRecordCount {
            get {
                return this.PaymentRecordCountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordCountField, value) != true)) {
                    this.PaymentRecordCountField = value;
                    this.RaisePropertyChanged("PaymentRecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentRecordTotalAmount {
            get {
                return this.PaymentRecordTotalAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordTotalAmountField, value) != true)) {
                    this.PaymentRecordTotalAmountField = value;
                    this.RaisePropertyChanged("PaymentRecordTotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public EAMITestClient.EAMISvcRef.PaymentExchangeEntity PayerInfo {
            get {
                return this.PayerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerInfoField, value) != true)) {
                    this.PayerInfoField = value;
                    this.RaisePropertyChanged("PayerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Collections.Generic.List<EAMITestClient.EAMISvcRef.PaymentRecord> PaymentRecordList {
            get {
                return this.PaymentRecordListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecordListField, value) != true)) {
                    this.PaymentRecordListField = value;
                    this.RaisePropertyChanged("PaymentRecordList");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionType", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    public enum TransactionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentSubmissionRequest = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentSubmissionResponse = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StatusInquiryRequest = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StatusInquiryResponse = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectedPaymentInquiryRequest = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectedPaymentInquiryResponse = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentExchangeEntity", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentExchangeEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityIDField;
        
        private string EntityIDSuffixField;
        
        private string EntityIDTypeField;
        
        private string NameField;
        
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        private string AddressCityField;
        
        private string AddressStateField;
        
        private string AddressZipField;
        
        private string EINField;
        
        private string VendorTypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EntityID {
            get {
                return this.EntityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIDField, value) != true)) {
                    this.EntityIDField = value;
                    this.RaisePropertyChanged("EntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EntityIDSuffix {
            get {
                return this.EntityIDSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIDSuffixField, value) != true)) {
                    this.EntityIDSuffixField = value;
                    this.RaisePropertyChanged("EntityIDSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EntityIDType {
            get {
                return this.EntityIDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIDTypeField, value) != true)) {
                    this.EntityIDTypeField = value;
                    this.RaisePropertyChanged("EntityIDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string AddressCity {
            get {
                return this.AddressCityField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressCityField, value) != true)) {
                    this.AddressCityField = value;
                    this.RaisePropertyChanged("AddressCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string AddressState {
            get {
                return this.AddressStateField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStateField, value) != true)) {
                    this.AddressStateField = value;
                    this.RaisePropertyChanged("AddressState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string AddressZip {
            get {
                return this.AddressZipField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressZipField, value) != true)) {
                    this.AddressZipField = value;
                    this.RaisePropertyChanged("AddressZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string EIN {
            get {
                return this.EINField;
            }
            set {
                if ((object.ReferenceEquals(this.EINField, value) != true)) {
                    this.EINField = value;
                    this.RaisePropertyChanged("EIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string VendorTypeCode {
            get {
                return this.VendorTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorTypeCodeField, value) != true)) {
                    this.VendorTypeCodeField = value;
                    this.RaisePropertyChanged("VendorTypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRecord", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentRecord : EAMITestClient.EAMISvcRef.BaseRecord {
        
        private string PaymentRecNumberExtField;
        
        private string PaymentTypeField;
        
        private System.DateTime PaymentDateField;
        
        private string AmountField;
        
        private string FiscalYearField;
        
        private EAMITestClient.EAMISvcRef.PaymentExchangeEntity PayeeInfoField;
        
        private string IndexCodeField;
        
        private string ObjectDetailCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectAgencyCodeField;
        
        private string PCACodeField;
        
        private string ApprovedByField;
        
        private string PaymentSetNumberField;
        
        private string PaymentSetNumberExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachmentField;
        
        private System.Collections.Generic.List<EAMITestClient.EAMISvcRef.FundingDetail> FundingDetailListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentRecNumberExt {
            get {
                return this.PaymentRecNumberExtField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecNumberExtField, value) != true)) {
                    this.PaymentRecNumberExtField = value;
                    this.RaisePropertyChanged("PaymentRecNumberExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string FiscalYear {
            get {
                return this.FiscalYearField;
            }
            set {
                if ((object.ReferenceEquals(this.FiscalYearField, value) != true)) {
                    this.FiscalYearField = value;
                    this.RaisePropertyChanged("FiscalYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public EAMITestClient.EAMISvcRef.PaymentExchangeEntity PayeeInfo {
            get {
                return this.PayeeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeInfoField, value) != true)) {
                    this.PayeeInfoField = value;
                    this.RaisePropertyChanged("PayeeInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string IndexCode {
            get {
                return this.IndexCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexCodeField, value) != true)) {
                    this.IndexCodeField = value;
                    this.RaisePropertyChanged("IndexCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ObjectDetailCode {
            get {
                return this.ObjectDetailCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectDetailCodeField, value) != true)) {
                    this.ObjectDetailCodeField = value;
                    this.RaisePropertyChanged("ObjectDetailCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ObjectAgencyCode {
            get {
                return this.ObjectAgencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectAgencyCodeField, value) != true)) {
                    this.ObjectAgencyCodeField = value;
                    this.RaisePropertyChanged("ObjectAgencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PCACode {
            get {
                return this.PCACodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PCACodeField, value) != true)) {
                    this.PCACodeField = value;
                    this.RaisePropertyChanged("PCACode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovedByField, value) != true)) {
                    this.ApprovedByField = value;
                    this.RaisePropertyChanged("ApprovedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string PaymentSetNumber {
            get {
                return this.PaymentSetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSetNumberField, value) != true)) {
                    this.PaymentSetNumberField = value;
                    this.RaisePropertyChanged("PaymentSetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string PaymentSetNumberExt {
            get {
                return this.PaymentSetNumberExtField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSetNumberExtField, value) != true)) {
                    this.PaymentSetNumberExtField = value;
                    this.RaisePropertyChanged("PaymentSetNumberExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public byte[] Attachment {
            get {
                return this.AttachmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentField, value) != true)) {
                    this.AttachmentField = value;
                    this.RaisePropertyChanged("Attachment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Collections.Generic.List<EAMITestClient.EAMISvcRef.FundingDetail> FundingDetailList {
            get {
                return this.FundingDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.FundingDetailListField, value) != true)) {
                    this.FundingDetailListField = value;
                    this.RaisePropertyChanged("FundingDetailList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRecord", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentRecordStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentRecordStatusPlus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentRecord))]
    public partial class BaseRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PaymentRecNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> GenericNameValueListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentRecNumber {
            get {
                return this.PaymentRecNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecNumberField, value) != true)) {
                    this.PaymentRecNumberField = value;
                    this.RaisePropertyChanged("PaymentRecNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Collections.Generic.Dictionary<string, string> GenericNameValueList {
            get {
                return this.GenericNameValueListField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericNameValueListField, value) != true)) {
                    this.GenericNameValueListField = value;
                    this.RaisePropertyChanged("GenericNameValueList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRecordStatus", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EAMITestClient.EAMISvcRef.PaymentRecordStatusPlus))]
    public partial class PaymentRecordStatus : EAMITestClient.EAMISvcRef.BaseRecord {
        
        private string PaymentRecNumberExtField;
        
        private string PaymentSetNumberField;
        
        private string PaymentSetNumberExtField;
        
        private string StatusCodeField;
        
        private System.DateTime StatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNoteField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentRecNumberExt {
            get {
                return this.PaymentRecNumberExtField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRecNumberExtField, value) != true)) {
                    this.PaymentRecNumberExtField = value;
                    this.RaisePropertyChanged("PaymentRecNumberExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentSetNumber {
            get {
                return this.PaymentSetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSetNumberField, value) != true)) {
                    this.PaymentSetNumberField = value;
                    this.RaisePropertyChanged("PaymentSetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentSetNumberExt {
            get {
                return this.PaymentSetNumberExtField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentSetNumberExtField, value) != true)) {
                    this.PaymentSetNumberExtField = value;
                    this.RaisePropertyChanged("PaymentSetNumberExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusNote {
            get {
                return this.StatusNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNoteField, value) != true)) {
                    this.StatusNoteField = value;
                    this.RaisePropertyChanged("StatusNote");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRecordStatusPlus", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PaymentRecordStatusPlus : EAMITestClient.EAMISvcRef.PaymentRecordStatus {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimScheduleNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClaimScheduleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarrantNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarrantAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WarrantDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimScheduleNumber {
            get {
                return this.ClaimScheduleNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimScheduleNumberField, value) != true)) {
                    this.ClaimScheduleNumberField = value;
                    this.RaisePropertyChanged("ClaimScheduleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ClaimScheduleDate {
            get {
                return this.ClaimScheduleDateField;
            }
            set {
                if ((this.ClaimScheduleDateField.Equals(value) != true)) {
                    this.ClaimScheduleDateField = value;
                    this.RaisePropertyChanged("ClaimScheduleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string WarrantNumber {
            get {
                return this.WarrantNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WarrantNumberField, value) != true)) {
                    this.WarrantNumberField = value;
                    this.RaisePropertyChanged("WarrantNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string WarrantAmount {
            get {
                return this.WarrantAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.WarrantAmountField, value) != true)) {
                    this.WarrantAmountField = value;
                    this.RaisePropertyChanged("WarrantAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime WarrantDate {
            get {
                return this.WarrantDateField;
            }
            set {
                if ((this.WarrantDateField.Equals(value) != true)) {
                    this.WarrantDateField = value;
                    this.RaisePropertyChanged("WarrantDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundingDetail", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class FundingDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FundingSourceNameField;
        
        private string FFPAmountField;
        
        private string SGFAmountField;
        
        private string FiscalYearField;
        
        private string FiscalQuarterField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> GenericNameValueListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FundingSourceName {
            get {
                return this.FundingSourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FundingSourceNameField, value) != true)) {
                    this.FundingSourceNameField = value;
                    this.RaisePropertyChanged("FundingSourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string FFPAmount {
            get {
                return this.FFPAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.FFPAmountField, value) != true)) {
                    this.FFPAmountField = value;
                    this.RaisePropertyChanged("FFPAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string SGFAmount {
            get {
                return this.SGFAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.SGFAmountField, value) != true)) {
                    this.SGFAmountField = value;
                    this.RaisePropertyChanged("SGFAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string FiscalYear {
            get {
                return this.FiscalYearField;
            }
            set {
                if ((object.ReferenceEquals(this.FiscalYearField, value) != true)) {
                    this.FiscalYearField = value;
                    this.RaisePropertyChanged("FiscalYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string FiscalQuarter {
            get {
                return this.FiscalQuarterField;
            }
            set {
                if ((object.ReferenceEquals(this.FiscalQuarterField, value) != true)) {
                    this.FiscalQuarterField = value;
                    this.RaisePropertyChanged("FiscalQuarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Collections.Generic.Dictionary<string, string> GenericNameValueList {
            get {
                return this.GenericNameValueListField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericNameValueListField, value) != true)) {
                    this.GenericNameValueListField = value;
                    this.RaisePropertyChanged("GenericNameValueList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingRequest", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenderIDField;
        
        private string ReceiverIDField;
        
        private System.DateTime ClientTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDField, value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string ReceiverID {
            get {
                return this.ReceiverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDField, value) != true)) {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ClientTimeStamp {
            get {
                return this.ClientTimeStampField;
            }
            set {
                if ((this.ClientTimeStampField.Equals(value) != true)) {
                    this.ClientTimeStampField = value;
                    this.RaisePropertyChanged("ClientTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResponse", Namespace="http://schemas.datacontract.org/2004/07/OHC.EAMI.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class PingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenderIDField;
        
        private string ReceiverIDField;
        
        private System.DateTime ServerTimeStampField;
        
        private System.DateTime ClientTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDField, value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string ReceiverID {
            get {
                return this.ReceiverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDField, value) != true)) {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ServerTimeStamp {
            get {
                return this.ServerTimeStampField;
            }
            set {
                if ((this.ServerTimeStampField.Equals(value) != true)) {
                    this.ServerTimeStampField = value;
                    this.RaisePropertyChanged("ServerTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime ClientTimeStamp {
            get {
                return this.ClientTimeStampField;
            }
            set {
                if ((this.ClientTimeStampField.Equals(value) != true)) {
                    this.ClientTimeStampField = value;
                    this.RaisePropertyChanged("ClientTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dhcsintranet/EAMI/", ConfigurationName="EAMISvcRef.IEAMIServiceOperations")]
    public interface IEAMIServiceOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentSubmission", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentSubmissionResponse")]
        EAMITestClient.EAMISvcRef.PaymentSubmissionResponse EAMIPaymentSubmission(EAMITestClient.EAMISvcRef.PaymentSubmissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentSubmission", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentSubmissionResponse")]
        System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.PaymentSubmissionResponse> EAMIPaymentSubmissionAsync(EAMITestClient.EAMISvcRef.PaymentSubmissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentStatusInquiry", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentStatusInquiryResponse")]
        EAMITestClient.EAMISvcRef.PaymentStatusInquiryResponse EAMIPaymentStatusInquiry(EAMITestClient.EAMISvcRef.PaymentStatusInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentStatusInquiry", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIPaymentStatusInquiryResponse")]
        System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.PaymentStatusInquiryResponse> EAMIPaymentStatusInquiryAsync(EAMITestClient.EAMISvcRef.PaymentStatusInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIRejectedPaymentInquiry", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIRejectedPaymentInquiryRespons" +
            "e")]
        EAMITestClient.EAMISvcRef.RejectedPaymentInquiryResponse EAMIRejectedPaymentInquiry(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIRejectedPaymentInquiry", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/EAMIRejectedPaymentInquiryRespons" +
            "e")]
        System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.RejectedPaymentInquiryResponse> EAMIRejectedPaymentInquiryAsync(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/Ping", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/PingResponse")]
        EAMITestClient.EAMISvcRef.PingResponse Ping(EAMITestClient.EAMISvcRef.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dhcsintranet/EAMI/IEAMIServiceOperations/Ping", ReplyAction="http://dhcsintranet/EAMI/IEAMIServiceOperations/PingResponse")]
        System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.PingResponse> PingAsync(EAMITestClient.EAMISvcRef.PingRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEAMIServiceOperationsChannel : EAMITestClient.EAMISvcRef.IEAMIServiceOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EAMIServiceOperationsClient : System.ServiceModel.ClientBase<EAMITestClient.EAMISvcRef.IEAMIServiceOperations>, EAMITestClient.EAMISvcRef.IEAMIServiceOperations {
        
        public EAMIServiceOperationsClient() {
        }
        
        public EAMIServiceOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EAMIServiceOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAMIServiceOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAMIServiceOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EAMITestClient.EAMISvcRef.PaymentSubmissionResponse EAMIPaymentSubmission(EAMITestClient.EAMISvcRef.PaymentSubmissionRequest request) {
            return base.Channel.EAMIPaymentSubmission(request);
        }
        
        public System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.PaymentSubmissionResponse> EAMIPaymentSubmissionAsync(EAMITestClient.EAMISvcRef.PaymentSubmissionRequest request) {
            return base.Channel.EAMIPaymentSubmissionAsync(request);
        }
        
        public EAMITestClient.EAMISvcRef.PaymentStatusInquiryResponse EAMIPaymentStatusInquiry(EAMITestClient.EAMISvcRef.PaymentStatusInquiryRequest request) {
            return base.Channel.EAMIPaymentStatusInquiry(request);
        }
        
        public System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.PaymentStatusInquiryResponse> EAMIPaymentStatusInquiryAsync(EAMITestClient.EAMISvcRef.PaymentStatusInquiryRequest request) {
            return base.Channel.EAMIPaymentStatusInquiryAsync(request);
        }
        
        public EAMITestClient.EAMISvcRef.RejectedPaymentInquiryResponse EAMIRejectedPaymentInquiry(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryRequest request) {
            return base.Channel.EAMIRejectedPaymentInquiry(request);
        }
        
        public System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.RejectedPaymentInquiryResponse> EAMIRejectedPaymentInquiryAsync(EAMITestClient.EAMISvcRef.RejectedPaymentInquiryRequest request) {
            return base.Channel.EAMIRejectedPaymentInquiryAsync(request);
        }
        
        public EAMITestClient.EAMISvcRef.PingResponse Ping(EAMITestClient.EAMISvcRef.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public System.Threading.Tasks.Task<EAMITestClient.EAMISvcRef.PingResponse> PingAsync(EAMITestClient.EAMISvcRef.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
    }
}
